export const SET_USER = "SET_USER";
export const GET_PRODUCTS = "GET_PRODUCTS";
export const SET_PRODUCT_TO_CART = "SET_PRODUCT_TO_CART";
export const REMOVE_PRODUCT_FROM_CART = "REMOVE_PRODUCT_FROM_CART";
export const GET_ORDER_HISTORY = "GET_ORDER_HISTORY";
